// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// kde_bandwidth_silverman
arma::mat kde_bandwidth_silverman(const arma::mat& ref_sample);
RcppExport SEXP _nicher_kde_bandwidth_silverman(SEXP ref_sampleSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type ref_sample(ref_sampleSEXP);
    rcpp_result_gen = Rcpp::wrap(kde_bandwidth_silverman(ref_sample));
    return rcpp_result_gen;
END_RCPP
}
// kde_eval_cpp
arma::vec kde_eval_cpp(const arma::mat& query, const arma::mat& ref, const arma::mat& H);
RcppExport SEXP _nicher_kde_eval_cpp(SEXP querySEXP, SEXP refSEXP, SEXP HSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type query(querySEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type ref(refSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type H(HSEXP);
    rcpp_result_gen = Rcpp::wrap(kde_eval_cpp(query, ref, H));
    return rcpp_result_gen;
END_RCPP
}
// loglik_presenceonly_cpp
double loglik_presenceonly_cpp(const arma::mat& sam1, const arma::mat& sam2, const arma::vec& mu, const arma::mat& S);
RcppExport SEXP _nicher_loglik_presenceonly_cpp(SEXP sam1SEXP, SEXP sam2SEXP, SEXP muSEXP, SEXP SSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type sam1(sam1SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type sam2(sam2SEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type S(SSEXP);
    rcpp_result_gen = Rcpp::wrap(loglik_presenceonly_cpp(sam1, sam2, mu, S));
    return rcpp_result_gen;
END_RCPP
}
// loglik_unweighted_cpp
double loglik_unweighted_cpp(const arma::mat& sam1, const arma::mat& sam2, const arma::vec& mu, const arma::mat& L);
RcppExport SEXP _nicher_loglik_unweighted_cpp(SEXP sam1SEXP, SEXP sam2SEXP, SEXP muSEXP, SEXP LSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type sam1(sam1SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type sam2(sam2SEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type L(LSEXP);
    rcpp_result_gen = Rcpp::wrap(loglik_unweighted_cpp(sam1, sam2, mu, L));
    return rcpp_result_gen;
END_RCPP
}
// loglik_weighted_cpp
double loglik_weighted_cpp(const arma::mat& sam1, const arma::mat& sam2, const arma::vec& mu, const arma::mat& S, const arma::vec& weights);
RcppExport SEXP _nicher_loglik_weighted_cpp(SEXP sam1SEXP, SEXP sam2SEXP, SEXP muSEXP, SEXP SSEXP, SEXP weightsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type sam1(sam1SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type sam2(sam2SEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type S(SSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type weights(weightsSEXP);
    rcpp_result_gen = Rcpp::wrap(loglik_weighted_cpp(sam1, sam2, mu, S, weights));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_nicher_kde_bandwidth_silverman", (DL_FUNC) &_nicher_kde_bandwidth_silverman, 1},
    {"_nicher_kde_eval_cpp", (DL_FUNC) &_nicher_kde_eval_cpp, 3},
    {"_nicher_loglik_presenceonly_cpp", (DL_FUNC) &_nicher_loglik_presenceonly_cpp, 4},
    {"_nicher_loglik_unweighted_cpp", (DL_FUNC) &_nicher_loglik_unweighted_cpp, 4},
    {"_nicher_loglik_weighted_cpp", (DL_FUNC) &_nicher_loglik_weighted_cpp, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_nicher(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
