// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cvine_cholesky
NumericMatrix cvine_cholesky(NumericVector v, int d, double eta);
RcppExport SEXP _nicher_cvine_cholesky(SEXP vSEXP, SEXP dSEXP, SEXP etaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type v(vSEXP);
    Rcpp::traits::input_parameter< int >::type d(dSEXP);
    Rcpp::traits::input_parameter< double >::type eta(etaSEXP);
    rcpp_result_gen = Rcpp::wrap(cvine_cholesky(v, d, eta));
    return rcpp_result_gen;
END_RCPP
}
// kde_gaussian_rcpp
NumericVector kde_gaussian_rcpp(const NumericMatrix& x, const NumericMatrix& data);
RcppExport SEXP _nicher_kde_gaussian_rcpp(SEXP xSEXP, SEXP dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type data(dataSEXP);
    rcpp_result_gen = Rcpp::wrap(kde_gaussian_rcpp(x, data));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_nicher_cvine_cholesky", (DL_FUNC) &_nicher_cvine_cholesky, 3},
    {"_nicher_kde_gaussian_rcpp", (DL_FUNC) &_nicher_kde_gaussian_rcpp, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_nicher(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
