# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cvine_cholesky_cpp <- function(v, d, eta = 1.0) {
    .Call(`_nicher_cvine_cholesky`, v, d, eta)
}

kde_gaussian_rcpp <- function(x, data) {
    .Call(`_nicher_kde_gaussian_rcpp`, x, data)
}

loglik_niche_chol_cpp <- function(mu, L, env_occ, env_m) {
    .Call(`_nicher_loglik_niche_chol_cpp`, mu, L, env_occ, env_m)
}

loglik_niche_chol_cpp_2d <- function(mu, L, env_occ, env_m) {
    .Call(`_nicher_loglik_niche_chol_cpp_2d`, mu, L, env_occ, env_m)
}

loglik_niche_cpp <- function(mu, S, env_occ, env_m) {
    .Call(`_nicher_loglik_niche_cpp`, mu, S, env_occ, env_m)
}

