# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cvine_cholesky_cpp <- function(v, d, eta = 1.0) {
    .Call(`_nicher_cvine_cholesky`, v, d, eta)
}

kde_gaussian_2d_cpp <- function(x, data) {
    .Call(`_nicher_kde_gaussian_2d_cpp`, x, data)
}

kde_gaussian_eigen_cpp <- function(x, data) {
    .Call(`_nicher_kde_gaussian_eigen_cpp`, x, data)
}

loglik_niche_chol_cpp <- function(mu, L, env_occ, env_m) {
    .Call(`_nicher_loglik_niche_chol_cpp`, mu, L, env_occ, env_m)
}

loglik_niche_math_presence_only_cpp <- function(theta, env_occ, eta = 1.0) {
    .Call(`_nicher_loglik_niche_math_presence_only_cpp`, theta, env_occ, eta)
}

loglik_niche_math_weighted_cpp <- function(theta, env_occ, M_den, w_occ, w_den, eta = 1.0) {
    .Call(`_nicher_loglik_niche_math_weighted_cpp`, theta, env_occ, M_den, w_occ, w_den, eta)
}

loglik_niche_math_weighted_grad_cpp <- function(theta, env_occ, M_den, w_occ, w_den, eta = 1.0, gradstep_rel = 1e-6, gradstep_abs = 1e-8) {
    .Call(`_nicher_loglik_niche_math_weighted_grad_cpp`, theta, env_occ, M_den, w_occ, w_den, eta, gradstep_rel, gradstep_abs)
}

loglik_niche_presence_only_cpp <- function(mu, L, env_occ) {
    .Call(`_nicher_loglik_niche_presence_only_cpp`, mu, L, env_occ)
}

loglik_niche_weighted_integrated_cpp <- function(mu, L, env_occ, env_m, den_idx = NULL, kde_idx = NULL, precomp_w_den = NULL, neg = TRUE) {
    .Call(`_nicher_loglik_niche_weighted_integrated_cpp`, mu, L, env_occ, env_m, den_idx, kde_idx, precomp_w_den, neg)
}

create_niche_obj_ptr <- function(env_occ, env_m = NULL, eta = 1.0, likelihood = "weighted", den_idx = NULL, kde_idx = NULL, precomp_w_occ = NULL, precomp_w_den = NULL, grad = "central", gradstep = as.numeric( c(1e-6, 1e-8))) {
    .Call(`_nicher_create_niche_obj_ptr`, env_occ, env_m, eta, likelihood, den_idx, kde_idx, precomp_w_occ, precomp_w_den, grad, gradstep)
}

#' Habitat-suitability kernel (parallel, zero-copy)
#'
#' Evaluates the standardized multivariate-normal density
#' \eqn{S(x) = \exp(-\tfrac12 (x-\mu)^\top \Sigma^{-1} (x-\mu))} for each
#' row of a column-major flat environmental buffer. Uses
#' \pkg{RcppParallel}'s \code{parallelFor} over locations.
#'
#' @param env_dat_vec Numeric vector. Flat column-major buffer of length
#'   \code{n_loc * p}; entry for location \code{l} variable \code{k} sits
#'   at index \code{l + n_loc * k}.
#' @param env_dat_dims Integer vector \code{c(n_loc, p)}.
#' @param mu Numeric vector of length \code{p}: niche centroid.
#' @param L_inv Numeric matrix \code{p x p}: inverse of the lower
#'   Cholesky factor of \eqn{\Sigma}. Precomputed R-side once.
#' @param return_log Logical. If \code{FALSE} (default) returns
#'   suitability in \eqn{(0, 1]}; if \code{TRUE} returns
#'   \eqn{\log S(x) \le 0}.
#' @param num_threads Integer. \code{0} (default) leaves
#'   \code{RcppParallel}'s global thread state unchanged.
#'
#' @return Numeric vector of length \code{n_loc}.
#'
#' @keywords internal
niche_suitability_cpp <- function(env_dat_vec, env_dat_dims, mu, L_inv, return_log = FALSE, num_threads = 0L) {
    .Call(`_nicher_niche_suitability_cpp`, env_dat_vec, env_dat_dims, mu, L_inv, return_log, num_threads)
}

